# config.yaml
appId: com.bdykun.onlypawsapp.dev

executionOrder:
  continueOnFailure: false # default is true
  flowsOrder:
    - loginError
    - login
    - searchAndFollowProfile
    - exploreFollowProfile
    - searchProfileAndViewPage
    - addPostComment
    - savePost
    - likePost
    - addPostCommentLike
    - addPostCommentReply
    - ownPostsShowReports
    - viewCommentLikeNotification # this has to be first in notification tests
    - viewCommentReplyNotification
    - viewFollowNotification
    - viewCommentNestedReply
    - createFeedback
    - changeProfile
    - editProfile
    - feedReportedPostHidden
    - createNewProfile
    - logOut
